apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    build: dc-pipeline
  name: dc-pipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  runPolicy: Serial
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        def tag,altTag

        pipeline {
          agent any
          stages{
            stage('Build in Dev') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject("dc-dev") {
                      openshift.startBuild("metro", "--wait=true")
                    }
                  }
                }
              }
            }
            stage('Test in Dev') {
              steps {
                sleep 5
              }
            }
            stage('Deploy to Prod (non-live)') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject("dc-prod") {
                      def route = openshift.selector("route", "metro-prod").object()
                      def backends = []
                      backends.add(route.spec.to)
                      backends.addAll(route.spec.alternateBackends)
                      def svc = backends.find {it.weight == 100}
                      tag = svc.name == "metro-green" ? "blue" : "green"
                      altTag = svc.name == "metro-green" ? "green" : "blue"
                      openshift.tag("dc-dev/metro:latest", "dc-prod/metro:prod-${tag}")
                      openshift.selector("dc", "metro-${tag}").rollout().latest()
                      openshift.selector("dc", "metro-${tag}").rollout().status('--watch')
                    }
                  }
                }
              }
            }
            stage('Integration Test in Prod (non-live)') {
              steps {
                sleep 5
              }
            }
            stage('Approve Go Live') {
              steps {
                timeout(time:15, unit:'MINUTES') {
                  input message: "Go Live in Production (switch to new version)?", ok: "Go Live"
                }
              }
            }
            stage('Make Live in Prod') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject("dc-prod") {
                      openshift.set("route-backends", "metro-prod", "--adjust", "metro-${tag}=100%")
                      openshift.set("route-backends", "metro-pre-prod", "--adjust", "metro-${altTag}=100%")
                    }
                  }
                }
              }
            }
          }
        }
    type: JenkinsPipeline
  triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
